/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GestionFicheros;


import java.io.File;
import java.util.LinkedList;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rosendo
 */
public class VentGesArchivos extends javax.swing.JFrame {

    /**
     * Creates new form VentGesArchivos
     */
    public VentGesArchivos() {
        initComponents();
// Ordenado por el nombre        
        ModTablaArchivos modArch = (ModTablaArchivos) tbARcOrigen.getModel();
        TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<TableModel>(modArch);
        tbARcOrigen.setRowSorter(elQueOrdena);
        
        ModTablaDestino modDest = (ModTablaDestino) tbArcDestino.getModel();
        TableRowSorter<TableModel> elQueOrdena2 = new TableRowSorter<TableModel>(modDest);
        tbArcDestino.setRowSorter(elQueOrdena2);
        
        TableColumn columna = tbArcDestino.getColumnModel().getColumn(1);
        columna.setCellEditor(new DestinoCellEditor(listaDirectorios));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbDirOrigen = new javax.swing.JLabel();
        lbDirDestino = new javax.swing.JLabel();
        tfDirOrigen = new javax.swing.JTextField();
        tfDirDestino = new javax.swing.JTextField();
        scPanOrigen = new javax.swing.JScrollPane();
        tbARcOrigen = new javax.swing.JTable();
        scPaneDestino = new javax.swing.JScrollPane();
        tbArcDestino = new javax.swing.JTable();
        btHaciaDestino = new javax.swing.JButton();
        btHaciaOrigen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de Archivos");

        lbDirOrigen.setText("Dir.Origen : ");
        lbDirOrigen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDirOrigenMouseClicked(evt);
            }
        });

        lbDirDestino.setText("Dir.Destino :");
        lbDirDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDirDestinoMouseClicked(evt);
            }
        });

        tfDirOrigen.setEnabled(false);
        tfDirOrigen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfDirOrigenMouseClicked(evt);
            }
        });

        tfDirDestino.setEnabled(false);
        tfDirDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfDirDestinoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbDirOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDirDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfDirOrigen)
                    .addComponent(tfDirDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDirOrigen)
                    .addComponent(tfDirOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDirDestino)
                    .addComponent(tfDirDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbARcOrigen.setModel(new ModTablaArchivos());
        scPanOrigen.setViewportView(tbARcOrigen);

        tbArcDestino.setModel(new ModTablaDestino());
        tbArcDestino.setColumnSelectionAllowed(true);
        scPaneDestino.setViewportView(tbArcDestino);
        tbArcDestino.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        btHaciaDestino.setText(">>>");
        btHaciaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHaciaDestinoActionPerformed(evt);
            }
        });

        btHaciaOrigen.setText("<<<");
        btHaciaOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHaciaOrigenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(scPanOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btHaciaDestino)
                            .addComponent(btHaciaOrigen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scPaneDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scPaneDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                            .addComponent(scPanOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btHaciaDestino)
                        .addGap(18, 18, 18)
                        .addComponent(btHaciaOrigen)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDirOrigenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfDirOrigenMouseClicked
        dirOrigen = Utilidad.obtenerDirectorio();
        if (dirOrigen != null)
        {
            tfDirOrigen.setText(dirOrigen.getAbsolutePath());
            ModTablaArchivos modelo = (ModTablaArchivos) tbARcOrigen.getModel();
            
            modelo.recarTabla(Utilidad.obtFicheroDeDirectorio(dirOrigen));
            
            modelo.fireTableDataChanged();
           
        } else {
            tfDirOrigen.setText("");
        }
    }//GEN-LAST:event_tfDirOrigenMouseClicked

    private void lbDirOrigenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDirOrigenMouseClicked
        dirOrigen = Utilidad.obtenerDirectorio();
        if (dirOrigen != null)
        {
            tfDirOrigen.setText(dirOrigen.getAbsolutePath());
        } else {
            tfDirOrigen.setText("");
        }
    }//GEN-LAST:event_lbDirOrigenMouseClicked

    private void lbDirDestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDirDestinoMouseClicked
        dirDestino = Utilidad.obtenerDirectorio();
        if (dirDestino != null)
        {
            tfDirDestino.setText(dirDestino.getAbsolutePath());
            listaDirectorios = Utilidad.obtDirectoriosDeDirectorio(dirDestino);
            TableColumn columna = tbArcDestino.getColumnModel().getColumn(1);
            columna.setCellEditor(new DestinoCellEditor(listaDirectorios));
            
        } else {
            tfDirDestino.setText("");
        }
    }//GEN-LAST:event_lbDirDestinoMouseClicked

    private void tfDirDestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfDirDestinoMouseClicked
        dirDestino = Utilidad.obtenerDirectorio();
        if (dirDestino != null)
        {
            tfDirDestino.setText(dirDestino.getAbsolutePath());
            listaDirectorios = Utilidad.obtDirectoriosDeDirectorio(dirDestino);
            TableColumn columna = tbArcDestino.getColumnModel().getColumn(1);
            columna.setCellEditor(new DestinoCellEditor(listaDirectorios));
            
        } else {
            tfDirDestino.setText("");
        }
    }//GEN-LAST:event_tfDirDestinoMouseClicked

    private void btHaciaOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHaciaOrigenActionPerformed
        
        boolean correcto = true;
        
        if (dirOrigen == null || dirDestino == null)
        {
            correcto = false;
            JOptionPane.showMessageDialog(null,"Directorio de origen y destino debe de estar seleccionado");
        }     
        
        if (tbArcDestino.getSelectedRow() == -1 && correcto)
        {
            correcto = false;
            JOptionPane.showMessageDialog(null,"Seleccionar una fila");
        }  
        
        if (correcto)
        {
            ModTablaDestino modDesde = (ModTablaDestino) tbArcDestino.getModel();
            
            int filSeleccion = tbArcDestino.getSelectedRow();
            
            int filReal = tbArcDestino.convertRowIndexToModel(filSeleccion);
            
            File fichero = modDesde.movSeleccion(filReal);
            
            ModTablaArchivos modHacia = (ModTablaArchivos) tbARcOrigen.getModel();
            
            modHacia.agreFichero(fichero);
            
            modHacia.fireTableDataChanged();
            
            modDesde.fireTableDataChanged();
        }
        
    }//GEN-LAST:event_btHaciaOrigenActionPerformed

    private void btHaciaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHaciaDestinoActionPerformed
        
        boolean correcto = true;
        
        if (dirOrigen == null || dirDestino == null)
        {
            correcto = false;
            JOptionPane.showMessageDialog(null,"Directorio de origen y destino debe de estar seleccionado");
        }       
        if (tbARcOrigen.getSelectedRow() == -1 && correcto)
        {
            correcto = false;
            JOptionPane.showMessageDialog(null,"Seleccionar una fila");
        }        
        if (correcto)
        {
            ModTablaArchivos modDesde = (ModTablaArchivos) tbARcOrigen.getModel();
            
            int filSeleccion = tbARcOrigen.getSelectedRow();
            int filReal = tbARcOrigen.convertRowIndexToModel(filSeleccion);
            
            File fichero = modDesde.movSeleccion(filReal);
            
            ModTablaDestino modHacia = (ModTablaDestino) tbArcDestino.getModel();
            
            modHacia.agreFichero(fichero);
            
            modHacia.fireTableDataChanged();
            
            modDesde.fireTableDataChanged();
        }
        
    }//GEN-LAST:event_btHaciaDestinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentGesArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentGesArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentGesArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentGesArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentGesArchivos().setVisible(true);
            }
        });
    }
    
    private File dirOrigen;
    private File dirDestino;
    private LinkedList<File> listaDirectorios;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHaciaDestino;
    private javax.swing.JButton btHaciaOrigen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDirDestino;
    private javax.swing.JLabel lbDirOrigen;
    private javax.swing.JScrollPane scPanOrigen;
    private javax.swing.JScrollPane scPaneDestino;
    private javax.swing.JTable tbARcOrigen;
    private javax.swing.JTable tbArcDestino;
    private javax.swing.JTextField tfDirDestino;
    private javax.swing.JTextField tfDirOrigen;
    // End of variables declaration//GEN-END:variables
}
